# Generated by Django 5.2.12 on 2026-04-22 20:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('business_type', models.CharField(choices=[('retail', 'Retail'), ('service', 'Service'), ('online', 'Online'), ('creator', 'Creator')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActiveBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_business', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_users', to='core.business')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business/logos/')),
                ('primary_color', models.CharField(blank=True, max_length=7)),
                ('secondary_color', models.CharField(blank=True, max_length=7)),
                ('theme', models.CharField(default='default', max_length=50)),
                ('about', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('tiktok', models.CharField(blank=True, max_length=100)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.business')),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('verification_code', models.CharField(db_index=True, max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0, help_text='Number of failed verification attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email Verification',
                'verbose_name_plural': 'Email Verifications',
                'db_table': 'email_verifications',
                'indexes': [models.Index(fields=['email', 'is_verified'], name='email_verif_email_9710ff_idx'), models.Index(fields=['verification_code'], name='email_verif_verific_c3df34_idx'), models.Index(fields=['expires_at'], name='email_verif_expires_fdd67c_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdentityState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_verified', models.BooleanField(default=False, help_text='Primary email address has been verified.')),
                ('email_verified_at', models.DateTimeField(blank=True, help_text='Timestamp when the primary email was verified.', null=True)),
                ('phone_verified', models.BooleanField(default=False, help_text='Primary phone number has been verified.')),
                ('phone_verified_at', models.DateTimeField(blank=True, help_text='Timestamp when the primary phone number was verified.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identity State',
                'verbose_name_plural': 'Identity States',
                'db_table': 'identity_states',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('tracking_mode', models.CharField(choices=[('quantity', 'Quantity'), ('serialized', 'Serialized')], default='quantity', max_length=20)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('low_stock_threshold', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.business')),
            ],
            options={
                'db_table': 'sales_product',
                'ordering': ['name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('sold', 'Sold'), ('returned', 'Returned'), ('damaged', 'Damaged')], default='in_stock', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_units', to='core.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.product')),
            ],
            options={
                'db_table': 'sales_product_unit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10)),
                ('value', models.CharField(max_length=255)),
                ('normalized_value', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recovery Method',
                'verbose_name_plural': 'Recovery Methods',
                'db_table': 'recovery_methods',
            },
        ),
        migrations.CreateModel(
            name='RecoveryChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('account_recovery', 'Account Recovery'), ('add_recovery_method', 'Add Recovery Method')], max_length=40)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10)),
                ('target_value', models.CharField(max_length=255)),
                ('target_display', models.CharField(blank=True, max_length=255)),
                ('code_hash', models.CharField(db_index=True, max_length=128)),
                ('code_last4', models.CharField(max_length=4)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_challenges', to=settings.AUTH_USER_MODEL)),
                ('recovery_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='core.recoverymethod')),
            ],
            options={
                'verbose_name': 'Recovery Challenge',
                'verbose_name_plural': 'Recovery Challenges',
                'db_table': 'recovery_challenges',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_locked', models.BooleanField(default=False, help_text='Locked roles cannot be renamed or deleted easily.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.business')),
            ],
        ),
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_roles', to='core.businessmember')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_members', to='core.role')),
            ],
        ),
        migrations.CreateModel(
            name='MemberInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('invite', 'Invite'), ('request', 'Request')], default='invite', max_length=20)),
                ('delivery', models.CharField(choices=[('email', 'Email'), ('local', 'Local')], default='local', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.business')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='core.role')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='core.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.role')),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('twitch', 'Twitch'), ('reddit', 'Reddit'), ('tumblr', 'Tumblr'), ('threads', 'Threads')], max_length=20)),
                ('account_username', models.CharField(max_length=255)),
                ('account_url', models.URLField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('connection_error', models.TextField(blank=True, null=True)),
                ('followers_count', models.IntegerField(default=0)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='core.business')),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
                'db_table': 'social_accounts',
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove'), ('set', 'Set')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='core.business')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='core.product')),
            ],
            options={
                'db_table': 'sales_stock_adjustment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, db_index=True, help_text='Primary verified phone number in canonical international format.', max_length=20, null=True, unique=True)),
                ('phone_country_code', models.CharField(blank=True, choices=[('TZ', 'Tanzania'), ('KE', 'Kenya'), ('UG', 'Uganda'), ('BI', 'Burundi'), ('RW', 'Rwanda'), ('CD', 'DRC'), ('ZM', 'Zambia')], help_text='Country code derived from the verified primary phone number.', max_length=2, null=True)),
                ('country', models.CharField(blank=True, choices=[('TZ', 'Tanzania'), ('KE', 'Kenya'), ('UG', 'Uganda'), ('BI', 'Burundi'), ('RW', 'Rwanda'), ('CD', 'DRC'), ('ZM', 'Zambia')], max_length=2, null=True)),
                ('completion_passed', models.BooleanField(default=False, help_text='Indicates whether the user has completed required profile fields.')),
                ('profile_image', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='BackupRecoveryCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('code_last4', models.CharField(max_length=4)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Recovery Code',
                'verbose_name_plural': 'Backup Recovery Codes',
                'db_table': 'backup_recovery_codes',
                'indexes': [models.Index(fields=['user', 'is_used'], name='backup_reco_user_id_ea5ec8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='businessmember',
            index=models.Index(fields=['user', 'business'], name='core_busine_user_id_926375_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businessmember',
            unique_together={('user', 'business')},
        ),
        migrations.AddIndex(
            model_name='identitystate',
            index=models.Index(fields=['user'], name='identity_st_user_id_68d34e_idx'),
        ),
        migrations.AddIndex(
            model_name='identitystate',
            index=models.Index(fields=['email_verified'], name='identity_st_email_v_ee9b46_idx'),
        ),
        migrations.AddIndex(
            model_name='identitystate',
            index=models.Index(fields=['phone_verified'], name='identity_st_phone_v_4f030f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'name'], name='sales_produ_busines_6d6758_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'tracking_mode'], name='sales_produ_busines_0322e0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'is_active'], name='sales_produ_busines_ea4baa_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_product_name_per_business'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('business', 'sku'), name='unique_product_sku_per_business_when_present'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['business', 'product'], name='sales_produ_busines_a17070_idx'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['business', 'status'], name='sales_produ_busines_fef4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['product', 'status'], name='sales_produ_product_c4c270_idx'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.UniqueConstraint(fields=('business', 'unique_id'), name='unique_product_unit_id_per_business'),
        ),
        migrations.AddIndex(
            model_name='recoverymethod',
            index=models.Index(fields=['user', 'method_type'], name='recovery_me_user_id_8ebb6d_idx'),
        ),
        migrations.AddIndex(
            model_name='recoverymethod',
            index=models.Index(fields=['user', 'is_verified'], name='recovery_me_user_id_0c87b4_idx'),
        ),
        migrations.AddIndex(
            model_name='recoverymethod',
            index=models.Index(fields=['user', 'is_active'], name='recovery_me_user_id_5bbb21_idx'),
        ),
        migrations.AddConstraint(
            model_name='recoverymethod',
            constraint=models.UniqueConstraint(fields=('user', 'method_type', 'normalized_value'), name='unique_user_recovery_method_value'),
        ),
        migrations.AddIndex(
            model_name='recoverychallenge',
            index=models.Index(fields=['user', 'purpose', 'status'], name='recovery_ch_user_id_05df67_idx'),
        ),
        migrations.AddIndex(
            model_name='recoverychallenge',
            index=models.Index(fields=['channel', 'target_value'], name='recovery_ch_channel_157c55_idx'),
        ),
        migrations.AddIndex(
            model_name='recoverychallenge',
            index=models.Index(fields=['expires_at'], name='recovery_ch_expires_bd214e_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['business'], name='core_role_busines_b1e4d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'business')},
        ),
        migrations.AddIndex(
            model_name='memberrole',
            index=models.Index(fields=['member'], name='core_member_member__9eaf65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='memberrole',
            unique_together={('member', 'role')},
        ),
        migrations.AddIndex(
            model_name='memberinvite',
            index=models.Index(fields=['business', 'email'], name='core_member_busines_d18c37_idx'),
        ),
        migrations.AddIndex(
            model_name='memberinvite',
            index=models.Index(fields=['business', 'target_user'], name='core_member_busines_36dcc6_idx'),
        ),
        migrations.AddIndex(
            model_name='memberinvite',
            index=models.Index(fields=['business', 'status'], name='core_member_busines_41c209_idx'),
        ),
        migrations.AddIndex(
            model_name='memberinvite',
            index=models.Index(fields=['type', 'status'], name='core_member_type_f78e60_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role'], name='core_rolepe_role_id_5506ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['business', 'platform'], name='social_acco_busines_71ea4a_idx'),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['is_connected', 'is_active'], name='social_acco_is_conn_727bd4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('business', 'platform', 'account_username')},
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['business', 'product'], name='sales_stock_busines_ad4c02_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['business', 'adjustment_type'], name='sales_stock_busines_33e2e0_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['created_at'], name='sales_stock_created_45be9f_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='user_profil_user_id_fbe33d_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['phone_number'], name='user_profil_phone_n_447d53_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['country'], name='user_profil_country_62f4a9_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['phone_country_code'], name='user_profil_phone_c_ba1fd6_idx'),
        ),
    ]
