# Generated by Django 5.2.6 on 2026-01-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_socialaccount_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='newsletter_subscription',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='notification_email',
        ),
    ]
