# Generated by Django 5.2.6 on 2026-01-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_newsletter_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='secondary_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_username',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='whatsapp_number',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, choices=[('TZ', 'Tanzania'), ('KE', 'Kenya'), ('UG', 'Uganda'), ('BI', 'Burundi'), ('RW', 'Rwanda'), ('CD', 'DRC'), ('ZM', 'Zambia')], max_length=2, null=True),
        ),
    ]
