# Generated by Django 5.2.6 on 2026-02-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_email_verification_enforcement'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountrecoverycode',
            new_name='account_rec_user_id_114b84_idx',
            old_name='account_rec_user_id_is_used_idx',
        ),
        migrations.RenameIndex(
            model_name='accountrecoverycode',
            new_name='account_rec_code_ha_a5e633_idx',
            old_name='account_rec_code_ha_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverification',
            new_name='email_verif_email_9710ff_idx',
            old_name='email_verif_email_id_verified_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverification',
            new_name='email_verif_verific_c3df34_idx',
            old_name='email_verif_verifi_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverification',
            new_name='email_verif_expires_fdd67c_idx',
            old_name='email_verif_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='recoverycontact',
            new_name='recovery_co_user_id_c1d3d8_idx',
            old_name='recovery_co_user_id_is_verif_idx',
        ),
        migrations.RenameIndex(
            model_name='recoverycontact',
            new_name='recovery_co_contact_4cba1e_idx',
            old_name='recovery_co_contact_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recovery_email',
            field=models.EmailField(blank=True, help_text='Alternative email for account recovery if primary email is lost', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recovery_mobile',
            field=models.CharField(blank=True, help_text='Alternative phone number for account recovery', max_length=20, null=True),
        ),
    ]
