# Generated by Django 5.2.6 on 2026-03-11 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ensure_userprofile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_locked', models.BooleanField(default=False, help_text='Locked roles cannot be renamed or deleted easily.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameIndex(
            model_name='passwordrecoverycode',
            new_name='password_re_user_id_73a8da_idx',
            old_name='password_recovery_codes_user_is_used_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordrecoverycode',
            new_name='password_re_code_faad64_idx',
            old_name='password_recovery_codes_code_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordrecoverycode',
            new_name='password_re_expires_852f88_idx',
            old_name='password_recovery_codes_expires_at_idx',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='recovery_email',
            field=models.EmailField(blank=True, help_text='Alternative email for account recovery if primary email is lost', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username_display',
            field=models.CharField(help_text='Username for display and future authentication', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.business'),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memberrole',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_roles', to='core.businessmember'),
        ),
        migrations.AddField(
            model_name='role',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.business'),
        ),
        migrations.AddField(
            model_name='memberrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_members', to='core.role'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='core.permission'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.role'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.AddIndex(
            model_name='businessmember',
            index=models.Index(fields=['user', 'business'], name='core_busine_user_id_926375_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businessmember',
            unique_together={('user', 'business')},
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['business'], name='core_role_busines_b1e4d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'business')},
        ),
        migrations.AddIndex(
            model_name='memberrole',
            index=models.Index(fields=['member'], name='core_member_member__9eaf65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='memberrole',
            unique_together={('member', 'role')},
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role'], name='core_rolepe_role_id_5506ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
    ]
