# Generated by Django 5.2.6 on 2026-03-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_businessmember_memberrole_permission_role_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='business',
            name='unique_business_slug_per_owner',
        ),
        migrations.RemoveField(
            model_name='business',
            name='owner',
        ),
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
