DEFAULT_ROLE_PERMISSIONS = {
    "owner": [
        "business.view",
        "business.update",
        "business.delete",
        "business.switch",
        "members.view",
        "members.invite",
        "members.update",
        "members.remove",
        "roles.view",
        "roles.create",
        "roles.update",
        "roles.delete",
        "roles.assign",
        "analytics.view",
        "social_accounts.view",
        "social_accounts.manage",
        "business_profile.view",
        "business_profile.update",
    ],
    "admin": [
        "business.view",
        "business.update",
        "business.switch",
        "members.view",
        "members.invite",
        "members.update",
        "roles.view",
        "analytics.view",
        "social_accounts.view",
        "social_accounts.manage",
        "business_profile.view",
        "business_profile.update",
    ],
    "manager": [
        "business.view",
        "business.switch",
        "members.view",
        "analytics.view",
        "social_accounts.view",
        "social_accounts.manage",
        "business_profile.view",
        "business_profile.update",
    ],
    "staff": [
        "business.view",
        "business.switch",
        "analytics.view",
        "social_accounts.view",
        "business_profile.view",
    ],
}